apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: misland-africa
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests: {storage: 5Gi}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: misland-africa
spec:
  selector: {app: misland-redis}
  ports:
    - {name: redis, port: 6379, targetPort: 6379}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: misland-africa
spec:
  replicas: 1
  selector:
    matchLabels: {app: misland-redis}
  template:
    metadata:
      labels: {app: misland-redis}
    spec:
      nodeSelector: {kubernetes.io/hostname: worker-prod-01}
      containers:
        - name: redis
          image: redis:6.2-alpine
          args: [redis-server, --appendonly, "yes"]
          ports:
            - {name: redis, containerPort: 6379}
          readinessProbe:
            exec: {command: [redis-cli, ping]}
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - {name: data, mountPath: /data}
      volumes:
        - name: data
          persistentVolumeClaim: {claimName: redis-data}
