// import cc from "../../.env";
import path from "path";

require('dotenv').config()

//require('dotenv').config({ path: '/home/sftdev/nyaga_workspace/reactjs/smartschool-web/.env' })

/**
 * Note: You must create custom environment variables beginning with REACT_APP_. 
 * Any other variables except NODE_ENV will be ignored to avoid accidentally exposing a
 *  private key on the machine that could have the same name. Changing any environment variables will 
 * require you to restart the development server if it is running.
 */


 /**
  * These REACT_APP env variables are loaded by the ./env-config.js included in the head of the index.html as also
  * generated by the bash script ./env.sh
  */
// console.log("server url : ", window._env_.REACT_APP_SERVER_URL)

//const SERVER_URL = "http://localhost";
//const SERVER_PORT = 4000;

const get_api_endpoint = (url) => {    
    /*
    var env = window._env_.REACT_APP_NODE_ENV;
    var SERVER_PORT = window._env_.REACT_APP_SERVER_PORT || 80;
    var SERVER_URL = window._env_.REACT_APP_SERVER_URL || window.location.hostname;//"http://localhost";
    if(env === "production"){
        SERVER_PORT =  window.location.port;
        const host = window.location.hostname;
        //var port = window.location.port;
        const protocol = window.location.protocol
        const server_url = `${protocol}//${host}`
        SERVER_URL = server_url;// window._env_.REACT_APP_SERVER_URL || window.location.hostname;//"http://localhost";
    }*/
    var SERVER_PORT = 8000;
    var SERVER_URL = "http://0.0.0.0";
    console.log("port ", SERVER_PORT);
    console.log("server url", SERVER_URL);
    return `${SERVER_URL}:${SERVER_PORT}/api/${url}`;
}

export default {
    get_api_endpoint
}