# Generated by Django 3.2 on 2020-08-31 09:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0003_auto_20200831_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='geom_linestring',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='feature',
            name='geom_polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
