# Generated by Django 3.2 on 2020-08-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0004_auto_20200831_0949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShapeFileLine',
        ),
        migrations.DeleteModel(
            name='ShapeFilePoint',
        ),
        migrations.DeleteModel(
            name='ShapeFilePolygon',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='geom_linestring',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='geom_multilinestring',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='geom_multipoint',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='geom_multipolygon',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='geom_point',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='geom_polygon',
        ),
        migrations.AlterField(
            model_name='shapefile',
            name='encoding',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='shapefile',
            name='srs',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
