# Generated by Django 3.2 on 2020-09-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0006_alter_shapefile_srs'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feature_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
