# Generated by Django 3.2 on 2020-09-03 08:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0007_feature_feature_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLevelOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_0', models.CharField(max_length=250)),
                ('gid_0', models.CharField(max_length=50)),
                ('name_1', models.CharField(max_length=250)),
                ('varname_1', models.CharField(blank=True, max_length=250)),
                ('nl_name_1', models.CharField(blank=True, max_length=250)),
                ('type_1', models.CharField(blank=True, max_length=250)),
                ('engtype_1', models.CharField(blank=True, max_length=250)),
                ('CC_1', models.CharField(blank=True, max_length=50)),
                ('hasc_1', models.CharField(blank=True, max_length=250)),
                ('cpu', models.CharField(blank=True, max_length=250)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='AdminLevelTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_0', models.CharField(max_length=250)),
                ('gid_0', models.CharField(max_length=250)),
                ('name_1', models.CharField(max_length=250)),
                ('nl_name_1', models.CharField(max_length=250)),
                ('gid_2', models.CharField(max_length=250)),
                ('name_2', models.CharField(max_length=250)),
                ('varname_2', models.CharField(max_length=250)),
                ('nl_name_2', models.CharField(max_length=250)),
                ('type_2', models.CharField(max_length=250)),
                ('engtype_2', models.CharField(max_length=250)),
                ('CC_2', models.CharField(max_length=250)),
                ('hasc_2', models.CharField(max_length=250)),
                ('cpu', models.CharField(max_length=250)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('admin_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ldms.adminlevelone')),
            ],
        ),
        migrations.CreateModel(
            name='AdminLevelZero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid_0', models.CharField(max_length=50)),
                ('name_0', models.CharField(max_length=250)),
                ('cpu', models.CharField(max_length=250)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='adminlevelone',
            name='admin_zero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ldms.adminlevelzero'),
        ),
    ]
