# Generated by Django 3.2 on 2020-09-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0009_adminlevelone_gid_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlevelone',
            name='CC_1',
        ),
        migrations.RemoveField(
            model_name='adminleveltwo',
            name='CC_2',
        ),
        migrations.AddField(
            model_name='adminlevelone',
            name='cc_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='adminleveltwo',
            name='cc_2',
            field=models.CharField(default='', max_length=250),
        ),
    ]
