# Generated by Django 3.2 on 2020-09-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0013_auto_20200904_1510'),
    ]

    operations = [
       
    ]
