# Generated by Django 3.2 on 2020-09-10 09:33

import django.core.validators
from django.db import migrations, models
import ldms.models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0014_delete_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('raster_year', models.PositiveIntegerField(blank=True, default=2020, validators=[django.core.validators.MinValueValidator, ldms.models.max_year_validator])),
                ('rasterfile', models.FileField(blank=True, null=True, upload_to='')),
                ('uperleftx', models.FloatField(blank=True, null=True)),
                ('uperlefty', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('scalex', models.FloatField(blank=True, null=True)),
                ('scaley', models.FloatField(blank=True, null=True)),
                ('skewx', models.FloatField(blank=True, null=True)),
                ('skewy', models.FloatField(blank=True, null=True)),
                ('numbands', models.IntegerField(blank=True, null=True)),
                ('srs_wkt', models.TextField(blank=True, null=True)),
                ('srid', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_zoom', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
