# Generated by Django 3.2 on 2020-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0015_raster'),
    ]

    operations = [
        migrations.AddField(
            model_name='raster',
            name='raster_type',
            field=models.CharField(blank=True, choices=[('LULC', 'Land Use/Land Cover'), ('Productivity', 'Productivity'), ('Carbon Stocks', 'Carbon Stocks'), ('Land Degradation', 'Land Degradation')], max_length=100),
        ),
    ]
