# Generated by Django 3.2 on 2020-09-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0016_raster_raster_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='raster',
            name='resolution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RasterValueMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True)),
                ('label', models.CharField(blank=True, max_length=20, null=True)),
                ('raster_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ldms.rastertype')),
            ],
        ),
    ]
