# Generated by Django 3.2 on 2020-09-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0018_alter_rastervaluemapping_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raster',
            name='raster_type',
        ),
    ]
