# Generated by Django 3.2 on 2020-09-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0019_remove_raster_raster_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='raster',
            name='raster_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ldms.rastertype'),
        ),
    ]
