# Generated by Django 3.2 on 2020-09-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0020_raster_raster_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastervaluemapping',
            name='label',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
