# Generated by Django 3.2 on 2020-09-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0021_alter_rastervaluemapping_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rastervaluemapping',
            name='label',
        ),
    ]
