# Generated by Django 3.2 on 2020-09-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0022_remove_rastervaluemapping_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastervaluemapping',
            name='label',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
