# Generated by Django 3.2 on 2020-09-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0024_rastervaluemapping_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastervaluemapping',
            name='color',
            field=models.CharField(blank=True, default='#FF0000', max_length=50, null=True),
        ),
    ]
