# Generated by Django 3.2 on 2020-09-20 10:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0026_auto_20200920_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionaladminlevel',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
        migrations.AlterField(
            model_name='regionaladminlevel',
            name='object_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='regionaladminlevel',
            name='shape_area',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='regionaladminlevel',
            name='shape_length',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
