# Generated by Django 3.2 on 2020-09-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0027_auto_20200920_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionaladminlevel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
