# Generated by Django 3.2 on 2020-09-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0028_regionaladminlevel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='raster',
            name='raster_category',
            field=models.CharField(blank=True, choices=[('LULC', 'LULC'), ('SOC', 'SOC'), ('NDVI', 'NDVI'), ('Rainfall', 'Rainfall')], default='', max_length=100),
        ),
    ]
