# Generated by Django 3.1 on 2020-10-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0029_raster_raster_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='raster',
            options={'ordering': ['name', 'raster_year']},
        ),
        migrations.AlterField(
            model_name='raster',
            name='raster_category',
            field=models.CharField(blank=True, choices=[('LULC', 'LULC'), ('SOC', 'SOC'), ('NDVI', 'NDVI'), ('Rainfall', 'Rainfall'), ('Ecological Units', 'Ecological Units')], default='', max_length=100),
        ),
    ]
