# Generated by Django 3.1 on 2020-10-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0030_auto_20201005_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='raster',
            name='raster_source',
            field=models.CharField(blank=True, choices=[('Custom', 'Custom'), ('Modis', 'Modis'), ('Landsat 7', 'Landsat 7'), ('Landsat 8', 'Landsat 8')], default='', max_length=50),
        ),
        # update raster_source
        migrations.RunSQL("""update ldms_raster set raster_source='Custom' where raster_category in ('LULC', 'Rainfall', 'SOC');"""),
        migrations.RunSQL("""update ldms_raster set raster_source='Modis' where raster_category='NDVI';""")
    ]
