# Generated by Django 3.1 on 2020-10-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0031_raster_raster_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='raster',
            name='admin_zero',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ldms.adminlevelzero'),
        ),
    ]
