# Generated by Django 3.1 on 2020-11-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0034_auto_20201112_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_port', models.IntegerField(help_text='Server port for the front end')),
                ('enable_guest_user_limit', models.BooleanField(default=False, help_text='If checked, guest users will process polygons upto a specific polygon size')),
                ('guest_user_polygon_size_limit', models.FloatField(help_text='Maximum size of polygon in hectares that anonymous users can process using the system')),
                ('enable_task_scheduling', models.BooleanField(help_text='If checked, user tasks will be scheduled')),
                ('enable_user_account_email_activation', models.BooleanField(help_text='If checked, users will activate their accounts via email')),
                ('email_host', models.CharField(help_text='Email server host', max_length=255)),
                ('email_host_user', models.CharField(help_text='Email server user', max_length=255)),
                ('email_host_password', models.CharField(help_text='Email server password', max_length=255)),
                ('email_host_protocol', models.CharField(blank=True, choices=[('TLS', 'TLS'), ('SSL', 'SSL')], default='TLS', help_text='Email protocol', max_length=20)),
                ('email_host_port', models.IntegerField(help_text='Email server port')),
            ],
            options={
                'verbose_name_plural': 'System Settings',
                'abstract': False,
            },
        ),
    ]
