# Generated by Django 3.1 on 2020-11-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0035_systemsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='frontend_port',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='task_results_url',
            field=models.CharField(default='http://0.0.0.0:8080/#/dashboard/results/', blank=False, help_text='Url to redirect user when results of scheduled task are available. Task id will be appended at the end after /', max_length=255),
        ),
    ]
