# Generated by Django 3.1 on 2020-11-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0036_auto_20201117_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_signedup_user_limit',
            field=models.BooleanField(default=False, help_text='If checked, Logged in users will process polygons upto a specific polygon size'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='signedup_user_polygon_size_limit',
            field=models.FloatField(default=1, help_text='Maximum size of polygon in hectares that Logged in users can process using the system'),
        ),
    ]
