# Generated by Django 3.1 on 2020-11-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0037_auto_20201118_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='raster_clipping_algorithm',
            field=models.CharField(blank=True, choices=[('All Touched', 'All Touched'), ('Pixel Center', 'Pixel Center')], default='All Touched', help_text='All Touched', max_length=20),
        ),
    ]
