# Generated by Django 3.1 on 2020-11-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0038_systemsettings_raster_clipping_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='raster_clipping_algorithm',
            field=models.CharField(blank=True, choices=[('All Touched', 'All Touched'), ('Pixel Center', 'Pixel Center')], default='All Touched:', help_text='All Touched=Include a pixel in the mask if it touches any of the shapes.\n        \t\tPixel Center= Include a pixel only if its center is within one of the shapes', max_length=20),
        ),
    ]
