# Generated by Django 3.1 on 2020-11-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0041_systemsettings_change_password_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(help_text='Name of image', max_length=255)),
                ('image_file', models.FileField(help_text='Attach image', max_length=255, upload_to='')),
                ('is_published', models.BooleanField(help_text='If not published, the image will not be shown to users')),
            ],
        ),
        migrations.AlterField(
            model_name='raster',
            name='raster_category',
            field=models.CharField(blank=True, choices=[('NDVI', 'NDVI'), ('LULC', 'LULC'), ('SOC', 'SOC'), ('Rainfall', 'Rainfall'), ('Aspect', 'Aspect'), ('Forest Loss', 'Forest Loss'), ('SAVI', 'SAVI'), ('MSAVI', 'MSAVI'), ('Evapotranspiration', 'Evapotranspiration'), ('Ecological Units', 'Ecological Units'), ('Soil Slope', 'Soil Slope'), ('Soil Depth', 'Soil Depth'), ('Soil Drainage', 'Soil Drainage'), ('Soil Parent Material', 'Soil Parent Material'), ('Soil Texture', 'Soil Texture'), ('Soil Rock Fragments', 'Soil Rock Fragments')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='raster',
            name='raster_source',
            field=models.CharField(blank=True, choices=[('LULC', 'LULC'), ('Modis', 'Modis'), ('Landsat 7', 'Landsat 7'), ('Landsat 8', 'Landsat 8'), ('Hansen', 'Hansen'), ('Sentinel 2', 'Sentinel 2')], default='', max_length=50),
        ),
    ]
