# Generated by Django 3.1 on 2020-11-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0042_auto_20201130_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_desc',
            field=models.TextField(blank=True, help_text='Image description'),
        ),
    ]
