# Generated by Django 3.1 on 2020-11-30 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ldms', '0043_auto_20201130_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('sort_order', models.IntegerField(default=0, help_text='The order you would like the topic to be displayed', verbose_name='Sort order')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['sort_order', 'topic_name'],
            },
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='raster_clipping_algorithm',
            field=models.CharField(blank=True, choices=[('All Touched', 'All Touched'), ('Pixel Center', 'Pixel Center')], default='All Touched:', help_text='All Touched=Include a pixel in the mask if it touches any of the shapes.\n\t\t\t\tPixel Center= Include a pixel only if its center is within one of the shapes', max_length=20),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question details', verbose_name='question')),
                ('answer', models.TextField(blank=True, help_text='The answer text', verbose_name='answer')),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Group Header')], default=0, help_text="Only questions with their status set to 'Active' will be displayed. Questions marked as 'Group Header are treated as views", verbose_name='status')),
                ('protected', models.BooleanField(default=False, help_text='Set true if this question is only visible to authenticated users', verbose_name='is protected')),
                ('sort_order', models.IntegerField(default=0, help_text='The order you would like this question to be displayed', verbose_name='Sort order')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on')),
                ('updated_on', models.DateTimeField(verbose_name='updated on')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ldms.topic', verbose_name='topic')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
        ),
    ]
