# Generated by Django 3.1 on 2020-11-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0044_auto_20201130_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='slug'),
        ),
    ]
