# Generated by Django 3.1 on 2020-11-30 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0046_auto_20201130_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updated_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated on'),
        ),
    ]
