# Generated by Django 3.1 on 2020-11-30 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0047_auto_20201130_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='updated on'),
        ),
    ]
