# Generated by Django 3.1 on 2020-12-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0048_auto_20201130_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputationThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource', models.CharField(choices=[('LULC', 'LULC'), ('Modis', 'Modis'), ('Landsat 7', 'Landsat 7'), ('Landsat 8', 'Landsat 8'), ('Hansen', 'Hansen'), ('Sentinel 2', 'Sentinel 2')], max_length=255, unique=True)),
                ('guest_user_threshold', models.FloatField(help_text='Maximum size of polygon in hectares that anonymous users can process using the system for the selected datasource')),
                ('enable_guest_user_limit', models.BooleanField(default=True, help_text='If checked, guest users will process polygons upto a specific polygon size')),
                ('authenticated_user_threshold', models.FloatField(help_text='Maximum size of polygon in hectares that anonymous users can process using the system for the selected datasource')),
                ('enable_signedup_user_limit', models.BooleanField(default=False, help_text='If checked, Logged in users will process polygons upto a specific polygon size')),
            ],
        ),
    ]
