# Generated by Django 3.2 on 2020-12-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0050_auto_20201206_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='orig_args',
            field=models.TextField(blank=True, help_text='Original payload as passed by the user before modification', null=True),
        ),
    ]
