# Generated by Django 3.2 on 2020-12-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0054_alter_systemsettings_enable_caching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='enable_caching',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_cache',
            field=models.BooleanField(blank=True, default=True, help_text='If enabled, results of computation will be cached for a period as specified by the cache limit field'),
        ),
    ]
