# Generated by Django 3.1 on 2021-02-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0057_auto_20210223_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customshapefile',
            old_name='file',
            new_name='shapefile',
        ),
        migrations.RenameField(
            model_name='customshapefile',
            old_name='name',
            new_name='shapefile_name',
        ),
    ]
