# Generated by Django 3.2 on 2021-03-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0058_auto_20210223_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='backend_port',
            field=models.IntegerField(default=80, help_text='Port from which the system is served', verbose_name='Backend port'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='override_backend_port',
            field=models.BooleanField(default=True, help_text='If checked, the system will override the default port and use the value of Backend port'),
        ),
    ]
