# Generated by Django 3.2 on 2021-12-10 15:42

import django.core.validators
from django.db import migrations, models
import ldms.models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0059_auto_20210322_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='backend_url',
            field=models.CharField(default='http://127.0.0.1/', help_text='Url of the backend. Do NOT include the port', max_length=255, null=True, verbose_name='Backend url'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_from_address',
            field=models.CharField(help_text='Sender Email Address', max_length=255, null=True, verbose_name='Sender Address'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_from_name',
            field=models.CharField(help_text='Sender Name', max_length=255, null=True, verbose_name='Sender Name'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_tiles',
            field=models.BooleanField(blank=True, default=False, help_text='If enabled, a WMS link will be returned for all analysis to allow rendering of tiles'),
        ),
        migrations.AlterField(
            model_name='raster',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='raster',
            name='raster_category',
            field=models.CharField(choices=[('NDVI', 'NDVI'), ('LULC', 'LULC'), ('SOC', 'SOC'), ('Rainfall', 'Rainfall'), ('Aspect', 'Aspect'), ('Forest Loss', 'Forest Loss'), ('SAVI', 'SAVI'), ('MSAVI', 'MSAVI'), ('Evapotranspiration', 'Evapotranspiration'), ('Ecological Units', 'Ecological Units'), ('Soil Slope', 'Soil Slope'), ('Soil Group', 'Soil Group'), ('Soil Drainage', 'Soil Drainage'), ('Soil Parent Material', 'Soil Parent Material'), ('Soil Texture', 'Soil Texture'), ('Soil Rock Fragments', 'Soil Rock Fragments'), ('Population Density', 'Population Density'), ('Land Use Density', 'Land Use Density'), ('Fire Risk', 'Fire Risk'), ('Erosion Protection', 'Erosion Protection'), ('Drought Resistance', 'Drought Resistance'), ('Plant Cover', 'Plant Cover'), ('Aridity Index', 'Aridity Index'), ('Tree Cover Loss', 'Tree Cover Loss'), ('Forest Activity Map', 'Forest Activity Map'), ('Vegetation Cover', 'Vegetation Cover'), ('Soil Roughness', 'Soil Roughness'), ('Soil Crust', 'Soil Crust'), ('Erodible Fraction', 'Erodible Fraction'), ('Climatic Erosivity', 'Climatic Erosivity'), ('Rainfall Erosivity', 'Rainfall Erosivity'), ('Soil Erodibility', 'Soil Erodibility'), ('Slope Steepness', 'Slope Steepness'), ('Cover Management', 'Cover Management'), ('Conservation Practices', 'Conservation Practices'), ('Geomorphology', 'Geomorphology'), ('Coastal Slope', 'Coastal Slope'), ('Sea Level Change', 'Sea Level Change'), ('Shoreline Erosion/Accretion', 'Shoreline Erosion/Accretion'), ('Tide Range', 'Tide Range'), ('Wave Height', 'Wave Height')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='raster',
            name='raster_source',
            field=models.CharField(choices=[('LULC', 'LULC'), ('Modis', 'Modis'), ('Landsat 7', 'Landsat 7'), ('Landsat 8', 'Landsat 8'), ('Hansen', 'Hansen'), ('Sentinel 2', 'Sentinel 2')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='raster',
            name='raster_year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator, ldms.models.max_year_validator]),
        ),
        migrations.AlterField(
            model_name='raster',
            name='rasterfile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
