# Generated by Django 3.1 on 2022-02-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0061_auto_20220205_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedcomputation',
            name='description',
        ),
        migrations.AddField(
            model_name='publishedcomputation',
            name='style',
            field=models.TextField(blank=True, help_text='Styled Layer Descriptor (SLD)', null=True),
        ),
    ]
