# Generated by Django 3.1 on 2022-10-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0063_auto_20220421_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='message',
            field=models.TextField(blank=True, help_text='The message sent to the user', null=True),
        ),
    ]
