# Generated by Django 3.1 on 2022-11-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0064_scheduledtask_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlevelzero',
            name='regional_admin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ldms.regionaladminlevel'),
        ),
    ]
