# Generated by Django 3.1 on 2022-11-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0065_adminlevelzero_regional_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlevelzero',
            name='region_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
