# Generated by Django 3.1 on 2022-11-16 15:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0066_adminlevelzero_region_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinentalAdminLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('shape_length', models.FloatField(blank=True, default=0, null=True)),
                ('shape_area', models.FloatField(blank=True, default=0, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='adminlevelone',
            options={'ordering': ('name_0', 'name_1')},
        ),
        migrations.AlterModelOptions(
            name='adminleveltwo',
            options={'ordering': ('name_0', 'name_1', 'name_2')},
        ),
        migrations.AlterModelOptions(
            name='adminlevelzero',
            options={'ordering': ('name_0',)},
        ),
        migrations.AlterModelOptions(
            name='regionaladminlevel',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='raster',
            name='admin_level',
            field=models.CharField(choices=[(-2, 'Continental'), (-1, 'Regional'), (0, 'Country')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='raster',
            name='regional_admin',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ldms.regionaladminlevel'),
        ),
        migrations.AddField(
            model_name='raster',
            name='continent_admin',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ldms.continentaladminlevel'),
        ),
        migrations.AddField(
            model_name='regionaladminlevel',
            name='continent_admin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ldms.continentaladminlevel'),
        ),
    ]
