# Generated by Django 3.1 on 2022-11-16 14:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.db import connection
from django.apps import apps
from common_gis.models import ContinentalAdminLevel, RegionalAdminLevel, AdminLevelZero
from ldms.load_vectors import import_continental_level_shape_files

def forwards(apps, schema_editor):
	"""
	Tag the existing rasters accordingly as per the admin_level.
	"""
	africa_id = None
	africa = ContinentalAdminLevel.objects.filter(name__iexact="Africa").first()
	if not africa:
		# attempt to import
		import_continental_level_shape_files()
		africa = ContinentalAdminLevel.objects.filter(name__iexact="Africa").first()
		if africa:
			africa_id = africa.id
	else:
		africa_id = africa.id
	oss_region = RegionalAdminLevel.objects.filter(name__iexact="OSS STATES").first()
	benin = AdminLevelZero.objects.get(name_0__iexact="Benin")
	with connection.cursor() as cursor: 
		# 1. update regional datasets
		sql = """
			Update ldms_raster set 
				admin_level=-1,
				regional_admin_id={0}
				WHERE admin_zero_id is null			
			""".format(oss_region.id)
		cursor.execute(sql)

		# 2. update country level datasets
		sql = """
			Update ldms_raster set 
				admin_level=0
				WHERE admin_zero_id is not null			
			"""
		cursor.execute(sql)

		# 3. update benin datasets to point to Africa
		sql = """
			Update ldms_raster set 
				admin_level=-2,
				admin_zero_id=null,
				continent_admin_id={0}
				WHERE admin_zero_id={1}			
			""".format(africa_id, benin.id)
		cursor.execute(sql)

		# 4. Update OSS countries with parent RegionalLevelAdmin
		sql = """
			Update ldms_adminlevelzero set 
				regional_admin_id={0}
				WHERE id != {1}			
			""".format(oss_region.id, benin.id)
		cursor.execute(sql)

		# 5. Update OSS region with parent ContinentalLevelAdmin
		sql = """
			Update ldms_regionaladminlevel set 
				continent_admin_id={0}
				WHERE id is not null			
			""".format(africa_id)
		cursor.execute(sql)

def backwards(apps, schema_editor):
	"""
	Untag the existing rasters accordingly as per the admin_level.
	No need to implement this method as some fields will have their original status lost already
	"""
	return

	africa_id = None
	africa = ContinentalAdminLevel.objects.filter(name="Africa").first()
	if not africa:
		africa_id = 1
	else:
		africa_id = africa.id
	oss_region = RegionalAdminLevel.objects.filter(name="OSS STATES").first()
	benin = AdminLevelZero.objects.get(name_0="Benin")
	with connection.cursor() as cursor: 
		# 1. undo update regional datasets
		sql = """
			Update ldms_raster set 
				regional_admin_id=null,
				admin_level=null,
				admin_zero_id=-1
				WHERE admin_zero is null			
			""".format(oss_region.id)
		cursor.execute(sql)

		# 2. undo update country level datasets
		sql = """
			Update ldms_raster set 
				admin_level=null
				WHERE admin_zero is not null			
			"""
		cursor.execute(sql)

		# 3. update benin datasets to point to Africa
		sql = """
			Update ldms_raster set 
				admin_level=-2
				continent_admin_id={0}
				WHERE admin_zero is not null			
			""".format(africa_id)
		cursor.execute(sql)

		# 3. Update OSS countries with parent RegionalLevelAdmin
		sql = """
			Update ldms_adminlevelzero set 
				regional_admin_id={0}
				WHERE id != {1}			
			""".format(oss_region.id, benin.id)
		cursor.execute(sql)

		# 4. Update OSS region with parent ContinentalLevelAdmin
		sql = """
			Update ldms_regionaladminlevel set 
				continent_admin_id={0}
				WHERE id is not null			
			""".format(africa_id)
		cursor.execute(sql)


def exec_sql(sql):
	with connection.cursor() as cursor:
		cursor.execute(sql) 
        
class Migration(migrations.Migration):

    dependencies = [
        ('ldms', '0067_auto_20221116_1542'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
		   [
			   migrations.RunPython(forwards, backwards)
		   ]
	   )
    ]