# Generated by Django 3.1 on 2023-01-13 08:23

from django.db import migrations
from django.db import connection
from django.apps import apps

src_prefix="common"
dest_prefix="communication"

def forwards(apps, schema_editor):
	changed_tables = [
		   'CommonSettings'
	   ]
	# model._meta.get_fields()

	same_tables = [
		'CommunicationLog',
	   ]

	tables_lst = []
	
	# Get active fields for a model. Some fields may have been dropped, so we dont want to select such
	for tbl in same_tables:
		model = apps.get_model('common', tbl)
		fields = " , ".join([x.column for x in model._meta.get_fields() if hasattr(x, 'column')])
		tables_lst.append([tbl.lower(), fields])

	# move settings
	with connection.cursor() as cursor: 
		# 1. copy specific fields in settings table
		sql = """
			INSERT INTO communication_communicationsettings (
					email_host,
					email_from_name,
					email_from_address,
					email_host_user,
					email_host_password,
					email_host_protocol,
					email_host_port,
					enable_email,
					enable_push_notifications,
					created_on,
					updated_on
				)
				SELECT
					email_host,
					email_from_name,
					email_from_address,
					email_host_user,
					email_host_password,
					email_host_protocol,
					email_host_port,
					CAST(1 AS BOOLEAN),
					CAST(1 AS BOOLEAN),
					Now(),
					Now()
				FROM
					common_commonsettings;
			"""
		cursor.execute(sql) 

		# 2. Import tables without GIS Tables	
		for table in tables_lst:
			sql = """
				INSERT INTO {dest}_{table} ({dest_fields}) SELECT {src_fields} FROM {src}_{table} 
				""".format(dest=dest_prefix, 
						   src=src_prefix,
						   table=table[0],
						   dest_fields=table[1],
						   src_fields=table[1].replace(" geom ", "ST_SetSRID(geom, 4326)")# Set SRID to allow copying of geom
						  )
			cursor.execute(sql) 

def backwards(apps, schema_editor):
	all_tables = [
		'CommunicationSettings',
		'CommunicationLog', 
	   ]

	for table in all_tables:
		exec_sql("""
			DELETE FROM {0}_{1}""".format(dest_prefix, table)			
		)

def exec_sql(sql):
	with connection.cursor() as cursor:
		cursor.execute(sql) 
	
class Migration(migrations.Migration):

	dependencies = [
		('ldms', '0070_ldmssettings'),
		('communication', '0002_auto_20230113_0809'),
	]

	operations = [
		 migrations.SeparateDatabaseAndState(
		   [
			   migrations.RunPython(forwards, backwards)
		   ]
	   )
	]
