# Generated by Django 3.1 on 2022-12-16 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('topic_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('sort_order', models.IntegerField(default=0, help_text='The order you would like the topic to be displayed', verbose_name='Sort order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_topic_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_topic_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['sort_order', 'topic_name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question details', verbose_name='question')),
                ('answer', models.TextField(blank=True, help_text='The answer text', verbose_name='answer')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='slug')),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Group Header')], default=0, help_text="Only questions with their status set to 'Active' will be displayed. Questions marked as 'Group Header are treated as views", verbose_name='status')),
                ('protected', models.BooleanField(default=False, help_text='Set true if this question is only visible to authenticated users', verbose_name='is protected')),
                ('sort_order', models.IntegerField(default=0, help_text='The order you would like this question to be displayed', verbose_name='Sort order')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created on')),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='updated on')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='common.topic', verbose_name='topic')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('image_name', models.CharField(help_text='Name of image', max_length=255)),
                ('image_file', models.FileField(help_text='Attach image', max_length=255, upload_to='')),
                ('image_desc', models.TextField(blank=True, help_text='Image description')),
                ('is_published', models.BooleanField(help_text='If not published, the image will not be shown to users')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_gallery_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_gallery_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='CommonSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('email_host', models.CharField(help_text='Email server host', max_length=255)),
                ('email_from_name', models.CharField(help_text='Sender Name', max_length=255, null=True, verbose_name='Sender Name')),
                ('email_from_address', models.CharField(help_text='Sender Email Address', max_length=255, null=True, verbose_name='Sender Address')),
                ('email_host_user', models.CharField(help_text='Email server user', max_length=255)),
                ('email_host_password', models.CharField(help_text='Email server password', max_length=255)),
                ('email_host_protocol', models.CharField(blank=True, choices=[('TLS', 'TLS'), ('SSL', 'SSL')], default='TLS', help_text='Email protocol', max_length=20)),
                ('email_host_port', models.IntegerField(help_text='Email server port')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_commonsettings_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_commonsettings_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'General Settings',
                'abstract': False,
            },
        ),
    ]
