# Generated by Django 3.1 on 2022-03-30 06:19

from django.db import migrations
from django.db import connection
from django.apps import apps

src_prefix="ldms"
dest_prefix="common"

def forwards(apps, schema_editor):
	changed_tables = [
		   'CommonSettings'
	   ]
	# model._meta.get_fields()

	same_tables = [
		'Gallery',
		'Topic',
		'Question',
	   ]

	tables_lst = []
	
	# Get active fields for a model. Some fields may have been dropped, so we dont want to select such
	for tbl in same_tables:
		model = apps.get_model('ldms', tbl)
		fields = " , ".join([x.column for x in model._meta.get_fields() if hasattr(x, 'column')])
		tables_lst.append([tbl.lower(), fields])

	with connection.cursor() as cursor: 
		# 1. copy specific fields in settings table
		sql = """
			INSERT INTO common_commonsettings (
					email_host,
					email_from_name,
					email_from_address,
					email_host_user,
					email_host_password,
					email_host_protocol,
					email_host_port
				)
				SELECT
					email_host,
					email_from_name,
					email_from_address,
					email_host_user,
					email_host_password,
					email_host_protocol,
					email_host_port
				FROM
					ldms_systemsettings;
			"""
		cursor.execute(sql) 

		# 2. Import tables without GIS Tables	
		for table in tables_lst:
			sql = """
				INSERT INTO {dest}_{table} ({dest_fields}) SELECT {src_fields} FROM {src}_{table} 
				""".format(dest=dest_prefix, 
						   src=src_prefix,
						   table=table[0],
						   dest_fields=table[1],
						   src_fields=table[1].replace(" geom ", "ST_SetSRID(geom, 4326)")# Set SRID to allow copying of geom
				          )
			cursor.execute(sql) 

def backwards(apps, schema_editor):
	all_tables = [
		'GISSettings',
		'Gallery',
		'Topic',
		'Question',
	   ]

	for table in all_tables:
		exec_sql("""
			DELETE FROM {0}_{1}""".format(dest_prefix, table)			
		)

def exec_sql(sql):
	with connection.cursor() as cursor:
		cursor.execute(sql) 
	
class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
         migrations.SeparateDatabaseAndState(
		   [
			   migrations.RunPython(forwards, backwards)
		   ]
	   )
    ]
