# Generated by Django 3.1 on 2022-12-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_update_backend_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonsettings',
            name='backend_url',
            field=models.CharField(default='http://0.0.0.0/', help_text='URL of server (without port) hosting the backend.', max_length=200, verbose_name='Backend url'),
        ),
        migrations.AlterField(
            model_name='commonsettings',
            name='override_backend_port',
            field=models.BooleanField(default=True, help_text='If checked, the system will override the default port and use the value of Backend port. Important when constructing URL of computed Raster'),
        ),
    ]
