# Generated by Django 3.1 on 2023-01-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20221221_0739'),
        ('ldms', '0071_auto_20230113_0823_migrate_communication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonsettings',
            name='email_from_address',
        ),
        migrations.RemoveField(
            model_name='commonsettings',
            name='email_from_name',
        ),
        migrations.RemoveField(
            model_name='commonsettings',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='commonsettings',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='commonsettings',
            name='email_host_port',
        ),
        migrations.RemoveField(
            model_name='commonsettings',
            name='email_host_protocol',
        ),
        migrations.RemoveField(
            model_name='commonsettings',
            name='email_host_user',
        ),
    ]
