# Generated by Django 3.1 on 2023-01-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20230113_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunicationLog',
        ),
    ]
