# Generated by Django 3.1 on 2023-10-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_delete_communicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_document',
            field=models.BooleanField(default=0, help_text='Is this a document'),
        ),
    ]
