# Generated by Django 3.1 on 2024-06-17 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0009_gallery_is_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('execution_name', models.CharField(help_text='Execution Name', max_length=255, null=True)),
                ('params', models.TextField(blank=True, help_text='Parameters to execution', null=True)),
                ('caller_id', models.CharField(blank=True, help_text='Calling object id', max_length=255, null=True)),
                ('caller_type', models.CharField(help_text='Calling object type', max_length=255, null=True)),
                ('caller_details', models.CharField(help_text='Calling object details', max_length=255, null=True)),
                ('execution_start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pre_execution_stats', models.JSONField(blank=True, help_text='Resources pre-execution', null=True)),
                ('post_execution_stats', models.JSONField(blank=True, help_text='Resources post-execution', null=True)),
                ('execution_end_time', models.DateTimeField(blank=True, null=True)),
                ('boot_time', models.DateTimeField(blank=True, help_text='Server boot time', null=True)),
                ('uptime_minutes', models.IntegerField(blank=True, default=False, help_text='Uptime in minutes?', null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, help_text='Has the monitoring completed ?', null=True)),
                ('is_critical_memory_usage', models.BooleanField(blank=True, default=False, help_text='Is memory usage critical?', null=True)),
                ('is_critical_cpu_usage', models.BooleanField(blank=True, default=False, help_text='Is cpu usage critical?', null=True)),
                ('is_critical_disk_usage', models.BooleanField(blank=True, default=False, help_text='Is disk usage critical?', null=True)),
                ('is_critical_temp', models.BooleanField(blank=True, default=False, help_text='Is temperature critical?', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_monitoringlog_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_monitoringlog_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commonsettings',
            name='enable_execution_monitoring',
            field=models.BooleanField(default=False, help_text='Enable monitoring of computations'),
        ),
        migrations.CreateModel(
            name='MonitoringLogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entry', models.DateTimeField(blank=True, null=True)),
                ('cpu', models.CharField(help_text='CPU utilized(%)', max_length=255, null=True)),
                ('memory', models.CharField(help_text='Memory usage (GB)', max_length=255, null=True)),
                ('disk', models.CharField(help_text='Disk usage (GB)', max_length=255, null=True)),
                ('highest_temp', models.CharField(help_text='Highest Temp (C)', max_length=255, null=True)),
                ('monitoring_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='common.monitoringlog')),
            ],
        ),
    ]
