# Generated by Django 3.1 on 2024-06-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20240617_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringlog',
            name='mem_profile',
            field=models.TextField(blank=True, help_text='Memory profile', null=True),
        ),
    ]
