# Generated by Django 3.1 on 2022-03-30 08:36

from django.db import migrations

from django.db import migrations
from django.db import connection
from django.apps import apps

src_prefix="ldms"
dest_prefix="common_gis"

def forwards(apps, schema_editor):
	changed_tables = [
		   'GISSettings'
	   ]

	# model._meta.get_fields()
	gis_tables = [
		['ContinentalAdminLevel', 'id, object_id, name, shape_length, shape_area, geom'],
		['RegionalAdminLevel', 'id, continent_admin_id, object_id, name, shape_length, shape_area, geom'],
		['AdminLevelZero', 'id, regional_admin_id, gid_0, name_0, region_name,  geom'],
		['AdminLevelOne', 'id, admin_zero_id, gid_0, name_0, gid_1, name_1, varname_1, nl_name_1, type_1, engtype_1, cc_1, hasc_1, cpu, geom'],
		['AdminLevelTwo', 'id, admin_one_id, gid_0, name_0, gid_1, name_1, nl_name_1, gid_2, name_2, varname_2, nl_name_2, type_2, engtype_2, cc_2, hasc_2, cpu, geom'],
	]
	same_tables = [
		'ComputationThreshold',
		'RasterType',
		'ScheduledTask',
		'RasterValueMapping',
		'Raster',
		'PublishedComputation',
		'PublishedComputationYear',
		# 'CustomShapeFile',
	   ]

	tables_lst = []
	
	# Get active fields for a model. Some fields may have been dropped, so we dont want to select such
	for tbl in same_tables:
		model = apps.get_model('ldms', tbl)
		fields = " , ".join([x.column for x in model._meta.get_fields() if hasattr(x, 'column')])
		tables_lst.append([tbl.lower(), fields])

	with connection.cursor() as cursor: 
		# 1. copy specific fields in settings table
		sql = """
			INSERT INTO common_gis_gissettings (
					enable_guest_user_limit,
					guest_user_polygon_size_limit,
					enable_signedup_user_limit,
					signedup_user_polygon_size_limit,
					enable_task_scheduling,
					task_results_url,
					raster_clipping_algorithm,
					enable_cache,
					cache_limit,
					override_backend_port,
					backend_url,
					backend_port,
					enable_tiles
				)
				SELECT
					enable_guest_user_limit,
					guest_user_polygon_size_limit,
					enable_signedup_user_limit,
					signedup_user_polygon_size_limit,
					enable_task_scheduling,
					task_results_url,
					raster_clipping_algorithm,
					enable_cache,
					cache_limit,
					override_backend_port,
					backend_url,
					backend_port,
					enable_tiles
				FROM
					ldms_systemsettings;
			"""
		cursor.execute(sql) 

		# 2. Import tables without GIS Tables	
		for table in tables_lst:
			sql = """
				INSERT INTO {dest}_{table} ({dest_fields}) SELECT {src_fields} FROM {src}_{table} 
				""".format(dest=dest_prefix, 
						   src=src_prefix,
						   table=table[0],
						   dest_fields=table[1],
						   src_fields=table[1].replace(" geom ", "ST_SetSRID(geom, 4326)")# Set SRID to allow copying of geom
				          )
			# print(sql)
			cursor.execute(sql) 

		# 3. import GIS Tables
		for table in gis_tables:
			sql = """
				INSERT INTO 
					common_gis_{0} 
					(
						{1}
					) 
				SELECT 
					{2}
				FROM 
					ldms_{0};
				""".format(
					table[0], #table_name
					table[1], #model fields
					table[1].replace("geom", "ST_SetSRID(geom, 4326)")# Set SRID to allow copying of geom
				)
			# print(sql)
			cursor.execute(sql) 

def backwards(apps, schema_editor):
	all_tables = [
		'GISSettings',
		'AdminLevelOne',
		'AdminLevelZero',
		'ComputationThreshold',
		'PublishedComputation',
		'RasterType',
		'RegionalAdminLevel',
		'ScheduledTask',
		'RasterValueMapping',
		'Raster',
		'PublishedComputationYear',
		'CustomShapeFile',
		'AdminLevelTwo',
        'RasterCache',
	   ]

	for table in all_tables:
		exec_sql("""
			DELETE FROM {2}_{0}""".format(table, src_prefix, dest_prefix)			
		)
	
def exec_sql(sql):
	with connection.cursor() as cursor:
		cursor.execute(sql) 

        
class Migration(migrations.Migration):

    dependencies = [
        ('common_gis', '0001_initial'),
		('ldms', '0067_auto_20221116_1542')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
		   [
			   migrations.RunPython(forwards, backwards)
		   ]
	   )
    ]
