# Generated by Django 3.1 on 2022-03-30 08:36

from django.db import migrations
from django.db import connection
from django.apps import apps

src_prefix="ldms"
dest_prefix="common_gis"

def forwards(apps, schema_editor):
	changed_tables = [
		   'GISSettings'
	   ]
	gis_tables = [
		['ContinentalAdminLevel', 'id, object_id, name, shape_length, shape_area, geom'],
		['RegionalAdminLevel', 'id, continent_admin_id, object_id, name, shape_length, shape_area, geom'],
		['AdminLevelZero', 'id, regional_admin_id, gid_0, name_0, region_name,  geom'],
		['AdminLevelOne', 'id, admin_zero_id, gid_0, name_0, gid_1, name_1, varname_1, nl_name_1, type_1, engtype_1, cc_1, hasc_1, cpu, geom'],
		['AdminLevelTwo', 'id, admin_one_id, gid_0, name_0, gid_1, name_1, nl_name_1, gid_2, name_2, varname_2, nl_name_2, type_2, engtype_2, cc_2, hasc_2, cpu, geom'],
	]
	same_tables = [
		'ComputationThreshold',
		'RasterType',
		'ScheduledTask',
		'RasterValueMapping',
		'Raster',
		'PublishedComputation',
		'PublishedComputationYear',
		# 'CustomShapeFile',
	   ]

	tables_lst = []
	tables_lst += changed_tables
	tables_lst += same_tables
	for tbl in gis_tables:
		tables_lst.append(tbl[0]) # append table name

	# reset SEQUENCE for the common_gis models that have imported data from the old tables
	# get max id from table
	for tbl in tables_lst:
		with connection.cursor() as cursor: 
			cursor.execute("SELECT id FROM {0}_{1} ORDER BY ID DESC LIMIT 1".format(dest_prefix, tbl))
			row = cursor.fetchone()
			if row:
				max_id = row[0]
				cursor.execute("ALTER SEQUENCE {0}_{1}_id_seq RESTART WITH {2};".format(dest_prefix, tbl.lower(), max_id+1))
	
def backwards(apps, schema_editor):
	pass
	
def exec_sql(sql):
	with connection.cursor() as cursor:
		cursor.execute(sql) 

        
class Migration(migrations.Migration):

    dependencies = [
        ('common_gis', '0002_auto_20221216_1836'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
		   [
			   migrations.RunPython(forwards, backwards)
		   ]
	   )
    ]
