# Generated by Django 3.1 on 2023-01-10 17:07

import common_gis.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_gis', '0004_remove_backend_port_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedcomputationyear',
            name='published_year',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator, common_gis.models.max_year_validator]),
        ),
        migrations.AlterField(
            model_name='raster',
            name='raster_year',
            field=models.PositiveIntegerField(default=2023, help_text='Year', validators=[django.core.validators.MinValueValidator, common_gis.models.max_year_validator]),
        ),
    ]
