# Generated by Django 3.1 on 2023-01-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_gis', '0005_auto_20230110_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raster',
            options={'ordering': ['-raster_year', 'name', 'raster_category', 'raster_source']},
        ),
        migrations.AlterModelOptions(
            name='rastertype',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='computationthreshold',
            name='datasource',
            field=models.CharField(choices=[('', ''), ('Hansen', 'Hansen'), ('LULC', 'LULC'), ('Landsat 7', 'Landsat 7'), ('Landsat 8', 'Landsat 8'), ('Modis', 'Modis'), ('Sentinel 2', 'Sentinel 2')], help_text='Datasource', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='raster',
            name='admin_level',
            field=models.CharField(choices=[('', ''), ('-2', 'Continental'), ('-1', 'Regional'), ('0', 'Country')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='raster',
            name='raster_category',
            field=models.CharField(choices=[('', ''), ('Aridity Index', 'Aridity Index'), ('Aspect', 'Aspect'), ('Climatic Erosivity', 'Climatic Erosivity'), ('Coastal Slope', 'Coastal Slope'), ('Conservation Practices', 'Conservation Practices'), ('Cover Management', 'Cover Management'), ('Drought Resistance', 'Drought Resistance'), ('Ecological Units', 'Ecological Units'), ('Erodible Fraction', 'Erodible Fraction'), ('Erosion Protection', 'Erosion Protection'), ('Evapotranspiration', 'Evapotranspiration'), ('Fire Risk', 'Fire Risk'), ('Forest Activity Map', 'Forest Activity Map'), ('Forest Loss', 'Forest Loss'), ('Geomorphology', 'Geomorphology'), ('LULC', 'LULC'), ('Land Use Density', 'Land Use Density'), ('MSAVI', 'MSAVI'), ('NDVI', 'NDVI'), ('Plant Cover', 'Plant Cover'), ('Population Density', 'Population Density'), ('Rainfall', 'Rainfall'), ('Rainfall Erosivity', 'Rainfall Erosivity'), ('SAVI', 'SAVI'), ('SOC', 'SOC'), ('Sea Level Change', 'Sea Level Change'), ('Shoreline Erosion/Accretion', 'Shoreline Erosion/Accretion'), ('Slope Steepness', 'Slope Steepness'), ('Soil Crust', 'Soil Crust'), ('Soil Drainage', 'Soil Drainage'), ('Soil Erodibility', 'Soil Erodibility'), ('Soil Group', 'Soil Group'), ('Soil Parent Material', 'Soil Parent Material'), ('Soil Rock Fragments', 'Soil Rock Fragments'), ('Soil Roughness', 'Soil Roughness'), ('Soil Slope', 'Soil Slope'), ('Soil Texture', 'Soil Texture'), ('Tide Range', 'Tide Range'), ('Tree Cover Loss', 'Tree Cover Loss'), ('Vegetation Cover', 'Vegetation Cover'), ('Wave Height', 'Wave Height')], default='', help_text='Raster Category', max_length=100),
        ),
        migrations.AlterField(
            model_name='raster',
            name='raster_source',
            field=models.CharField(choices=[('', ''), ('Hansen', 'Hansen'), ('LULC', 'LULC'), ('Landsat 7', 'Landsat 7'), ('Landsat 8', 'Landsat 8'), ('Modis', 'Modis'), ('Sentinel 2', 'Sentinel 2')], default='', help_text='Datasource', max_length=50),
        ),
    ]
