# Generated by Django 3.1 on 2023-10-21 23:43

import common_gis.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common_gis', '0006_auto_20230113_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('cache_key', models.TextField(help_text='Cache key')),
                ('custom_polygon', models.TextField(blank=True, help_text='Custom polygon', null=True)),
                ('computation_type', models.CharField(blank=True, help_text='The type of computation', max_length=255, null=True)),
                ('change_enum', models.CharField(blank=True, help_text='Change Enum applied', max_length=255, null=True)),
                ('datasource', models.CharField(choices=[('', ''), ('Hansen', 'Hansen'), ('LULC', 'LULC'), ('Landsat 7', 'Landsat 7'), ('Landsat 8', 'Landsat 8'), ('Modis', 'Modis'), ('Sentinel 2', 'Sentinel 2')], default='', help_text='Datasource', max_length=255)),
                ('nodata', models.FloatField(blank=True, default=0, null=True)),
                ('prefix', models.CharField(blank=True, help_text='Prefix to be prepended to resulting raster', max_length=255, null=True)),
                ('resolution', models.FloatField(blank=True, default=0, null=True)),
                ('subdir', models.CharField(blank=True, help_text='Subdirectory for the resulting raster', max_length=255, null=True)),
                ('raster_file', models.FileField(help_text='Computed raster file', null=True, upload_to='')),
                ('start_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator, common_gis.models.max_year_validator])),
                ('end_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator, common_gis.models.max_year_validator])),
                ('arguments', models.TextField(blank=True, help_text='Computation arguments', null=True)),
                ('results', models.TextField(blank=True, help_text='Results of the computation', null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('request', models.TextField(blank=True, null=True)),
                ('queue_msg', models.TextField(help_text='Message when computation is queued')),
                ('admin_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_level_one', to='common_gis.adminlevelone')),
                ('admin_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_level_two', to='common_gis.adminleveltwo')),
                ('admin_zero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_level_zero', to='common_gis.adminlevelzero')),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_gis.continentaladminlevel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_gis_computedresult_creator', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_gis.regionaladminlevel')),
            ],
            options={
                'ordering': ('created_on',),
            },
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='change_enum',
            field=models.CharField(blank=True, help_text='Change Enum applied', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publishedcomputation',
            name='computation_type',
            field=models.CharField(choices=[('Aridity Index', 'Aridity Index'), ('Climate Quality Index', 'Climate Quality Index'), ('Coastal Vulnerability Index', 'Coastal Vulnerability Index'), ('ESAI', 'ESAI'), ('Forest Carbon Emission', 'Forest Carbon Emission'), ('Forest Change', 'Forest Change'), ('Forest Fire', 'Forest Fire'), ('Forest Fire Risk', 'Forest Fire Risk'), ('ILSWE', 'ILSWE'), ('LULC', 'LULC'), ('LULC Change', 'LULC Change'), ('Land Degradation', 'Land Degradation'), ('Management Quality Index', 'Management Quality Index'), ('Productivity', 'Productivity'), ('Productivity Performance', 'Productivity Performance'), ('Productivity State', 'Productivity State'), ('Productivity Trajectory', 'Productivity Trajectory'), ('RUSLE', 'RUSLE'), ('SOC', 'SOC'), ('Soil Quality Index', 'Soil Quality Index'), ('Vegetation Quality Index', 'Vegetation Quality Index')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ScheduledPreComputation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('computation_type', models.CharField(choices=[('Aridity Index', 'Aridity Index'), ('Climate Quality Index', 'Climate Quality Index'), ('Coastal Vulnerability Index', 'Coastal Vulnerability Index'), ('ESAI', 'ESAI'), ('Forest Carbon Emission', 'Forest Carbon Emission'), ('Forest Change', 'Forest Change'), ('Forest Fire', 'Forest Fire'), ('Forest Fire Risk', 'Forest Fire Risk'), ('ILSWE', 'ILSWE'), ('LULC', 'LULC'), ('LULC Change', 'LULC Change'), ('Land Degradation', 'Land Degradation'), ('Management Quality Index', 'Management Quality Index'), ('Productivity', 'Productivity'), ('Productivity Performance', 'Productivity Performance'), ('Productivity State', 'Productivity State'), ('Productivity Trajectory', 'Productivity Trajectory'), ('RUSLE', 'RUSLE'), ('SOC', 'SOC'), ('Soil Quality Index', 'Soil Quality Index'), ('Vegetation Quality Index', 'Vegetation Quality Index')], default='', max_length=100)),
                ('change_enum', models.CharField(blank=True, help_text='Change Enum applied', max_length=255, null=True)),
                ('admin_level', models.CharField(choices=[('', ''), ('-2', 'Continental'), ('-1', 'Regional'), ('0', 'Country')], default=None, max_length=50, null=True)),
                ('datasource', models.CharField(choices=[('', ''), ('Hansen', 'Hansen'), ('LULC', 'LULC'), ('Landsat 7', 'Landsat 7'), ('Landsat 8', 'Landsat 8'), ('Modis', 'Modis'), ('Sentinel 2', 'Sentinel 2')], default='', help_text='Datasource', max_length=255, null=True)),
                ('start_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator, common_gis.models.max_year_validator])),
                ('end_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator, common_gis.models.max_year_validator])),
                ('started_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('', ''), ('Queued', 'Queued'), ('Processing', 'Processing'), ('Failed', 'Failed'), ('Succeeded', 'Succeeded')], default='', max_length=100)),
                ('args', models.TextField(blank=True, null=True)),
                ('method', models.CharField(max_length=128)),
                ('error', models.TextField(blank=True, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('admin_zero', models.ForeignKey(blank=True, default='', help_text='Country', null=True, on_delete=django.db.models.deletion.CASCADE, to='common_gis.adminlevelzero')),
                ('continent', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='common_gis.continentaladminlevel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_gis_scheduledprecomputation_creator', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, default='', help_text='Region', null=True, on_delete=django.db.models.deletion.CASCADE, to='common_gis.regionaladminlevel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_gis_scheduledprecomputation_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Scheduled PreComputations',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComputedResultItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('key', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, help_text='Pixel label', max_length=255, null=True)),
                ('count', models.IntegerField(help_text='Pixel count')),
                ('value', models.FloatField(help_text='Value of area')),
                ('custom_string_01', models.CharField(blank=True, help_text='String 01', max_length=255, null=True)),
                ('custom_string_02', models.CharField(blank=True, help_text='String 02', max_length=255, null=True)),
                ('custom_string_03', models.CharField(blank=True, help_text='String 03', max_length=255, null=True)),
                ('custom_string_04', models.CharField(blank=True, help_text='String 04', max_length=255, null=True)),
                ('custom_string_05', models.CharField(blank=True, help_text='String 05', max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_gis_computedresultitem_creator', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_gis.computedresult')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_gis_computedresultitem_updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('result',),
            },
        ),
        migrations.AddField(
            model_name='computedresult',
            name='scheduled_precomputation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_gis.scheduledprecomputation'),
        ),
        migrations.AddField(
            model_name='computedresult',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='common_gis_computedresult_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='scheduled_precomputation',
            field=models.ForeignKey(blank=True, default='', help_text='Scheduled PreComputation associated with this scheduled task', null=True, on_delete=django.db.models.deletion.CASCADE, to='common_gis.scheduledprecomputation'),
        ),
    ]
