# Generated by Django 3.1 on 2024-06-15 07:48

import common_gis.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_gis', '0007_auto_20231021_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedcomputationyear',
            name='published_year',
            field=models.PositiveIntegerField(default=2024, validators=[django.core.validators.MinValueValidator, common_gis.models.max_year_validator]),
        ),
        migrations.AlterField(
            model_name='raster',
            name='raster_year',
            field=models.PositiveIntegerField(default=2024, help_text='Year', validators=[django.core.validators.MinValueValidator, common_gis.models.max_year_validator]),
        ),
    ]
