# Generated by Django 3.1 on 2025-05-22 05:00

import common_gis.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_gis', '0008_auto_20240615_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='computationthreshold',
            name='enable_overall_user_limit',
            field=models.BooleanField(blank=True, default=False, help_text='If checked, users will not be able to process polygons beyond a specific polygon size'),
        ),
        migrations.AddField(
            model_name='computationthreshold',
            name='overall_user_threshold',
            field=models.FloatField(default=100000, help_text='Maximum size of polygon in hectares that all users can process using the system for the selected datasource'),
        ),
        migrations.AddField(
            model_name='gissettings',
            name='enable_overall_size_limit',
            field=models.BooleanField(default=False, help_text='If checked, users will not be able to process or schedule computations for polygons beyond a specific polygon size'),
        ),
        migrations.AddField(
            model_name='gissettings',
            name='overall_polygon_size_limit',
            field=models.FloatField(default=100000, help_text='Maximum size of polygon in hectares that a computation can be performed in the system'),
        ),
        migrations.AlterField(
            model_name='publishedcomputation',
            name='computation_type',
            field=models.CharField(choices=[('Aridity Index', 'Aridity Index'), ('Climate Quality Index', 'Climate Quality Index'), ('Coastal Erosion', 'Coastal Erosion'), ('Coastal Erosion - Geomorphology', 'Coastal Erosion - Geomorphology'), ('Coastal Erosion - Mean Tide Range', 'Coastal Erosion - Mean Tide Range'), ('Coastal Erosion - Mean Wave Height', 'Coastal Erosion - Mean Wave Height'), ('Coastal Erosion - Sea Level Rise', 'Coastal Erosion - Sea Level Rise'), ('Coastal Erosion - Shoreline Change', 'Coastal Erosion - Shoreline Change'), ('Coastal Erosion - Slope', 'Coastal Erosion - Slope'), ('ESAI', 'ESAI'), ('Forest Carbon Emission', 'Forest Carbon Emission'), ('Forest Change', 'Forest Change'), ('Forest Fire', 'Forest Fire'), ('Forest Fire Risk', 'Forest Fire Risk'), ('ILSWE', 'ILSWE'), ('ILSWE - Climate Erosivity', 'ILSWE - Climate Erosivity'), ('ILSWE - Soil Crust Factor', 'ILSWE - Soil Crust Factor'), ('ILSWE - Soil Erodible Fraction', 'ILSWE - Soil Erodible Fraction'), ('ILSWE - Soil Roughness', 'ILSWE - Soil Roughness'), ('ILSWE - Vegetation Cover', 'ILSWE - Vegetation Cover'), ('LULC', 'LULC'), ('LULC Change', 'LULC Change'), ('Land Degradation', 'Land Degradation'), ('Management Quality Index', 'Management Quality Index'), ('Productivity', 'Productivity'), ('Productivity Performance', 'Productivity Performance'), ('Productivity State', 'Productivity State'), ('Productivity Trajectory', 'Productivity Trajectory'), ('RUSLE', 'RUSLE'), ('RUSLE - Conservation Practice', 'RUSLE - Conservation Practice'), ('RUSLE - Cover Management', 'RUSLE - Cover Management'), ('RUSLE - Rainfall Erosivity', 'RUSLE - Rainfall Erosivity'), ('RUSLE - Slope Steepness', 'RUSLE - Slope Steepness'), ('RUSLE - Soil Erodibility', 'RUSLE - Soil Erodibility'), ('SOC', 'SOC'), ('Soil Quality Index', 'Soil Quality Index'), ('Vegetation Quality Index', 'Vegetation Quality Index')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='publishedcomputationyear',
            name='published_year',
            field=models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator, common_gis.models.max_year_validator]),
        ),
        migrations.AlterField(
            model_name='raster',
            name='raster_year',
            field=models.PositiveIntegerField(default=2025, help_text='Year', validators=[django.core.validators.MinValueValidator, common_gis.models.max_year_validator]),
        ),
        migrations.AlterField(
            model_name='scheduledprecomputation',
            name='computation_type',
            field=models.CharField(choices=[('Aridity Index', 'Aridity Index'), ('Climate Quality Index', 'Climate Quality Index'), ('Coastal Erosion', 'Coastal Erosion'), ('Coastal Erosion - Geomorphology', 'Coastal Erosion - Geomorphology'), ('Coastal Erosion - Mean Tide Range', 'Coastal Erosion - Mean Tide Range'), ('Coastal Erosion - Mean Wave Height', 'Coastal Erosion - Mean Wave Height'), ('Coastal Erosion - Sea Level Rise', 'Coastal Erosion - Sea Level Rise'), ('Coastal Erosion - Shoreline Change', 'Coastal Erosion - Shoreline Change'), ('Coastal Erosion - Slope', 'Coastal Erosion - Slope'), ('ESAI', 'ESAI'), ('Forest Carbon Emission', 'Forest Carbon Emission'), ('Forest Change', 'Forest Change'), ('Forest Fire', 'Forest Fire'), ('Forest Fire Risk', 'Forest Fire Risk'), ('ILSWE', 'ILSWE'), ('ILSWE - Climate Erosivity', 'ILSWE - Climate Erosivity'), ('ILSWE - Soil Crust Factor', 'ILSWE - Soil Crust Factor'), ('ILSWE - Soil Erodible Fraction', 'ILSWE - Soil Erodible Fraction'), ('ILSWE - Soil Roughness', 'ILSWE - Soil Roughness'), ('ILSWE - Vegetation Cover', 'ILSWE - Vegetation Cover'), ('LULC', 'LULC'), ('LULC Change', 'LULC Change'), ('Land Degradation', 'Land Degradation'), ('Management Quality Index', 'Management Quality Index'), ('Productivity', 'Productivity'), ('Productivity Performance', 'Productivity Performance'), ('Productivity State', 'Productivity State'), ('Productivity Trajectory', 'Productivity Trajectory'), ('RUSLE', 'RUSLE'), ('RUSLE - Conservation Practice', 'RUSLE - Conservation Practice'), ('RUSLE - Cover Management', 'RUSLE - Cover Management'), ('RUSLE - Rainfall Erosivity', 'RUSLE - Rainfall Erosivity'), ('RUSLE - Slope Steepness', 'RUSLE - Slope Steepness'), ('RUSLE - Soil Erodibility', 'RUSLE - Soil Erodibility'), ('SOC', 'SOC'), ('Soil Quality Index', 'Soil Quality Index'), ('Vegetation Quality Index', 'Vegetation Quality Index')], default='', max_length=100),
        ),
    ]
