# Generated by Django 3.1 on 2025-05-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_gis', '0009_auto_20250522_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gissettings',
            name='enable_overall_size_limit',
        ),
        migrations.RemoveField(
            model_name='gissettings',
            name='overall_polygon_size_limit',
        ),
        migrations.AddField(
            model_name='gissettings',
            name='enable_overall_user_limit',
            field=models.BooleanField(blank=True, default=False, help_text='If checked, users will not be able to process polygons beyond a specific polygon size'),
        ),
        migrations.AddField(
            model_name='gissettings',
            name='overall_user_threshold',
            field=models.FloatField(default=100000, help_text='Maximum size of polygon in hectares that all users can process using the system for the selected datasource'),
        ),
    ]
