# Generated by Django 3.1 on 2025-05-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_gis', '0010_auto_20250523_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gissettings',
            name='overall_user_threshold',
        ),
        migrations.AddField(
            model_name='gissettings',
            name='overall_polygon_size_limit',
            field=models.FloatField(default=100000, help_text='Maximum size of polygon in hectares that all users can process using the system for the selected datasource'),
        ),
    ]
